version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dokokasse-stack"
s3_bucket = "dokokasse-bucket"
s3_prefix = "dokokasse"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
